services:

  database:
    image: "${DATABASE}"
    volumes:
      - ${PROGRESSCFG}:/usr/dlc/progress.cfg
  
  backend:
    image: "${BACKEND}"
    volumes:
      - ${PROGRESSCFG}:/usr/dlc/progress.cfg
    labels:
      - "traefik.http.middlewares.replace-slashdata.replacepathregex.regex=^/data/(.*)"
      - "traefik.http.middlewares.replace-slashdata.replacepathregex.replacement=/web/$$1"
      - "traefik.http.routers.pas.rule=Host(`${DOMAIN}`) && PathPrefix(`/data`)"
      - "traefik.http.routers.pas.middlewares=replace-slashdata"
    depends_on:
      - database

  frontend:
    image: "${FRONTEND}"
    labels:
      - "traefik.http.routers.ui.rule=Host(`${DOMAIN}`)"
    depends_on:
      - backend

  router:
    image: traefik:latest
    command: 
      - "--api.insecure=true" 
      - "--providers.docker" 
    ports:
      - $HOSTPORT:80
      - 8080:8080  # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: sports2020-network
  